version: '2'

services:
  
  product-launch-db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=NDC_l0nd0n
    networks:
      - app-net

  product-launch-web:
    image: sixeyed/product-launch-web:v2
    ports:
      - "80:80"
    depends_on:
      - product-launch-db
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat